apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: gke-dbt
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: gke-dbt
    spec:
      containers:
      - name: gke-dbt
        image: gcr.io/PROJECT_ID/IMAGE:TAG
        command: ["dbt", "run"]
        resources:
          requests:
            cpu: 100m
          limits:
            cpu: 100m
        env:
        - name: GCP_PROJECT_ID
          value: velascoluis-test 
        - name: GCP_BQ_DATASET_ID
          value: warehouse 
